"""Initial migration

Revision ID: 7af2b1191811
Revises: 
Create Date: 2025-11-19 17:47:30.368590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af2b1191811'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnc',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bfs', sa.String(), nullable=False),
    sa.Column('n_cnc', sa.String(), nullable=True),
    sa.Column('subprefeitura', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('data_fiscalizacao', sa.DateTime(), nullable=True),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('prazo_hours', sa.Integer(), nullable=False),
    sa.Column('responsividade', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'URGENTE', 'REGULARIZADO', 'AGUARDANDO_VISTORIA', name='statuscnc'), nullable=False),
    sa.Column('situacao_cnc', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('coordenada', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.Column('fiscal_contratada', sa.String(), nullable=True),
    sa.Column('agente_fiscalizador', sa.String(), nullable=True),
    sa.Column('aplicou_multa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cnc_data_abertura', 'cnc', ['data_abertura'], unique=False)
    op.create_index('idx_cnc_status_prazo', 'cnc', ['status', 'prazo_hours'], unique=False)
    op.create_index(op.f('ix_cnc_aplicou_multa'), 'cnc', ['aplicou_multa'], unique=False)
    op.create_index(op.f('ix_cnc_bfs'), 'cnc', ['bfs'], unique=True)
    op.create_index(op.f('ix_cnc_data_abertura'), 'cnc', ['data_abertura'], unique=False)
    op.create_index(op.f('ix_cnc_status'), 'cnc', ['status'], unique=False)
    op.create_index(op.f('ix_cnc_subprefeitura'), 'cnc', ['subprefeitura'], unique=False)
    op.create_table('fiscais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('subprefeitura', sa.Enum('CV', 'JT', 'ST', 'MG', name='subprefeitura'), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('last_location', sa.JSON(), nullable=True),
    sa.Column('last_location_lat', sa.Float(), nullable=True),
    sa.Column('last_location_lng', sa.Float(), nullable=True),
    sa.Column('last_location_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fiscal_subpref_ativo', 'fiscais', ['subprefeitura', 'ativo'], unique=False)
    op.create_index(op.f('ix_fiscais_ativo'), 'fiscais', ['ativo'], unique=False)
    op.create_index(op.f('ix_fiscais_nome'), 'fiscais', ['nome'], unique=False)
    op.create_index(op.f('ix_fiscais_subprefeitura'), 'fiscais', ['subprefeitura'], unique=False)
    op.create_table('indicadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('IRD', 'IA', 'IF', 'IPT', 'ADC', name='tipoindicador'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('pontuacao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('periodo_inicial', sa.DateTime(), nullable=False),
    sa.Column('periodo_final', sa.DateTime(), nullable=False),
    sa.Column('subprefeitura', sa.Enum('CV', 'JT', 'ST', 'MG', name='subprefeitura'), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('detalhes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicador_subpref_periodo', 'indicadores', ['subprefeitura', 'periodo_inicial'], unique=False)
    op.create_index('idx_indicador_tipo_periodo', 'indicadores', ['tipo', 'periodo_inicial', 'periodo_final'], unique=False)
    op.create_index(op.f('ix_indicadores_calculated_at'), 'indicadores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_indicadores_periodo_inicial'), 'indicadores', ['periodo_inicial'], unique=False)
    op.create_index(op.f('ix_indicadores_subprefeitura'), 'indicadores', ['subprefeitura'], unique=False)
    op.create_index(op.f('ix_indicadores_tipo'), 'indicadores', ['tipo'], unique=False)
    op.create_table('acic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('n_acic', sa.String(), nullable=True),
    sa.Column('n_bfs', sa.String(), nullable=True),
    sa.Column('n_cnc', sa.String(), nullable=True),
    sa.Column('cnc_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('SOLICITACAO', 'CONFIRMADO', 'CANCELADO', name='statusacic'), nullable=True),
    sa.Column('data_fiscalizacao', sa.DateTime(), nullable=True),
    sa.Column('data_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('data_acic', sa.DateTime(), nullable=True),
    sa.Column('data_confirmacao', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao_status', sa.DateTime(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('agente_fiscalizador', sa.String(), nullable=True),
    sa.Column('contratada', sa.String(), nullable=True),
    sa.Column('regional', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_multa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('clausula_contratual', sa.String(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('coordenada_aceite', sa.String(), nullable=True),
    sa.Column('coordenada_resposta', sa.String(), nullable=True),
    sa.Column('coordenada_vistoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cnc_id'], ['cnc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_acic_data_acic', 'acic', ['data_acic'], unique=False)
    op.create_index('idx_acic_status', 'acic', ['status'], unique=False)
    op.create_index(op.f('ix_acic_data_acic'), 'acic', ['data_acic'], unique=False)
    op.create_index(op.f('ix_acic_n_acic'), 'acic', ['n_acic'], unique=False)
    op.create_table('sacs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protocolo', sa.String(), nullable=False),
    sa.Column('tipo_servico', sa.Enum('CAPINA', 'ENTULHO', 'ANIMAL_MORTO', 'MUTIRAO', 'VARRIACAO', 'BUEIRO', 'PAPELEIRAS', 'CATABAGULHO', 'PROPAGANDA', 'OUTROS', name='tiposervico'), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_ANALISE', 'AGUARDANDO_AGENDAMENTO', 'AGUARDANDO_REVISTORIA', 'NAO_PROCEDE', 'EM_EXECUCAO', 'EXECUTADO', 'CONFIRMAR_EXECUCAO', 'CONFIRMADA_EXECUCAO', 'NAO_CONFIRMADA_EXECUCAO', 'CONFIRMAR_FORA_ESCOPO', 'AGUARDANDO_CONFIRMACAO_EXECUCAO_PARCIAL', 'FINALIZADO', name='statussac'), nullable=False),
    sa.Column('subprefeitura', sa.Enum('CV', 'JT', 'ST', 'MG', name='subprefeitura'), nullable=False),
    sa.Column('endereco_text', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('domicilio_id', sa.String(), nullable=True),
    sa.Column('protocolo_origem', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_vistoria', sa.DateTime(), nullable=True),
    sa.Column('data_agendamento', sa.DateTime(), nullable=True),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('data_encerramento', sa.DateTime(), nullable=True),
    sa.Column('prazo_max_hours', sa.Integer(), nullable=False),
    sa.Column('fiscal_id', sa.UUID(), nullable=True),
    sa.Column('fotos_before', sa.JSON(), nullable=True),
    sa.Column('fotos_after', sa.JSON(), nullable=True),
    sa.Column('evidencias', sa.JSON(), nullable=True),
    sa.Column('flag_erro_regional', sa.Boolean(), nullable=True),
    sa.Column('inserted_from_csv', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fiscal_id'], ['fiscais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sac_data_criacao', 'sacs', ['data_criacao'], unique=False)
    op.create_index('idx_sac_status_subpref', 'sacs', ['status', 'subprefeitura'], unique=False)
    op.create_index(op.f('ix_sacs_data_agendamento'), 'sacs', ['data_agendamento'], unique=False)
    op.create_index(op.f('ix_sacs_data_criacao'), 'sacs', ['data_criacao'], unique=False)
    op.create_index(op.f('ix_sacs_data_execucao'), 'sacs', ['data_execucao'], unique=False)
    op.create_index(op.f('ix_sacs_flag_erro_regional'), 'sacs', ['flag_erro_regional'], unique=False)
    op.create_index(op.f('ix_sacs_protocolo'), 'sacs', ['protocolo'], unique=True)
    op.create_index(op.f('ix_sacs_status'), 'sacs', ['status'], unique=False)
    op.create_index(op.f('ix_sacs_subprefeitura'), 'sacs', ['subprefeitura'], unique=False)
    op.create_index(op.f('ix_sacs_tipo_servico'), 'sacs', ['tipo_servico'], unique=False)
    op.create_table('logs_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sac_id', sa.UUID(), nullable=False),
    sa.Column('status_anterior', sa.String(), nullable=True),
    sa.Column('status_novo', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sac_id'], ['sacs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_sac_created', 'logs_status', ['sac_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_logs_status_created_at'), 'logs_status', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_status_sac_id'), 'logs_status', ['sac_id'], unique=False)
    op.create_table('ouvidorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_chamado', sa.String(), nullable=False),
    sa.Column('numero_sei', sa.String(), nullable=True),
    sa.Column('sac_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('EM_EXECUCAO', 'OUVIDORIA_ENCERRADA', 'FINALIZADO', 'EXECUTADO', 'CONFIRMAR_EXECUCAO', name='statusouvidoria'), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('contratada', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('procedente', sa.String(), nullable=True),
    sa.Column('procedente_por_status', sa.String(), nullable=True),
    sa.Column('finalizado_como_fora_de_escopo', sa.String(), nullable=True),
    sa.Column('regional', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.Column('assunto', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('coordenadas', sa.String(), nullable=True),
    sa.Column('data_extracao_pdf', sa.DateTime(), nullable=True),
    sa.Column('data_alteracao_sac', sa.DateTime(), nullable=True),
    sa.Column('data_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('data_acao_de_agendar', sa.DateTime(), nullable=True),
    sa.Column('data_acionamento_agendamento', sa.DateTime(), nullable=True),
    sa.Column('data_acionamento_revistoria', sa.DateTime(), nullable=True),
    sa.Column('data_realizacao_vistoria', sa.DateTime(), nullable=True),
    sa.Column('data_acionamento_confirmacao_execucao', sa.DateTime(), nullable=True),
    sa.Column('data_realizacao_confirmacao_execucao', sa.DateTime(), nullable=True),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('data_ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('responsividade', sa.String(), nullable=True),
    sa.Column('responsividade_resposta', sa.String(), nullable=True),
    sa.Column('responsividade_execucao', sa.String(), nullable=True),
    sa.Column('sac_publicacao_no_prazo', sa.String(), nullable=True),
    sa.Column('classificacao_do_servico', sa.String(), nullable=True),
    sa.Column('data_reprova', sa.DateTime(), nullable=True),
    sa.Column('usuario_reprova', sa.String(), nullable=True),
    sa.Column('observacao_reprova', sa.Text(), nullable=True),
    sa.Column('usuario_execucao', sa.String(), nullable=True),
    sa.Column('usuario_vistoria_nao_procede', sa.String(), nullable=True),
    sa.Column('usuario_primeira_vistoria', sa.String(), nullable=True),
    sa.Column('usuario_agendamento', sa.String(), nullable=True),
    sa.Column('usuario_publicacao', sa.String(), nullable=True),
    sa.Column('fotos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sac_id'], ['sacs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ouvidoria_data_registro', 'ouvidorias', ['data_registro'], unique=False)
    op.create_index('idx_ouvidoria_status', 'ouvidorias', ['status'], unique=False)
    op.create_index(op.f('ix_ouvidorias_numero_chamado'), 'ouvidorias', ['numero_chamado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ouvidorias_numero_chamado'), table_name='ouvidorias')
    op.drop_index('idx_ouvidoria_status', table_name='ouvidorias')
    op.drop_index('idx_ouvidoria_data_registro', table_name='ouvidorias')
    op.drop_table('ouvidorias')
    op.drop_index(op.f('ix_logs_status_sac_id'), table_name='logs_status')
    op.drop_index(op.f('ix_logs_status_created_at'), table_name='logs_status')
    op.drop_index('idx_log_sac_created', table_name='logs_status')
    op.drop_table('logs_status')
    op.drop_index(op.f('ix_sacs_tipo_servico'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_subprefeitura'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_status'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_protocolo'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_flag_erro_regional'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_data_execucao'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_data_criacao'), table_name='sacs')
    op.drop_index(op.f('ix_sacs_data_agendamento'), table_name='sacs')
    op.drop_index('idx_sac_status_subpref', table_name='sacs')
    op.drop_index('idx_sac_data_criacao', table_name='sacs')
    op.drop_table('sacs')
    op.drop_index(op.f('ix_acic_n_acic'), table_name='acic')
    op.drop_index(op.f('ix_acic_data_acic'), table_name='acic')
    op.drop_index('idx_acic_status', table_name='acic')
    op.drop_index('idx_acic_data_acic', table_name='acic')
    op.drop_table('acic')
    op.drop_index(op.f('ix_indicadores_tipo'), table_name='indicadores')
    op.drop_index(op.f('ix_indicadores_subprefeitura'), table_name='indicadores')
    op.drop_index(op.f('ix_indicadores_periodo_inicial'), table_name='indicadores')
    op.drop_index(op.f('ix_indicadores_calculated_at'), table_name='indicadores')
    op.drop_index('idx_indicador_tipo_periodo', table_name='indicadores')
    op.drop_index('idx_indicador_subpref_periodo', table_name='indicadores')
    op.drop_table('indicadores')
    op.drop_index(op.f('ix_fiscais_subprefeitura'), table_name='fiscais')
    op.drop_index(op.f('ix_fiscais_nome'), table_name='fiscais')
    op.drop_index(op.f('ix_fiscais_ativo'), table_name='fiscais')
    op.drop_index('idx_fiscal_subpref_ativo', table_name='fiscais')
    op.drop_table('fiscais')
    op.drop_index(op.f('ix_cnc_subprefeitura'), table_name='cnc')
    op.drop_index(op.f('ix_cnc_status'), table_name='cnc')
    op.drop_index(op.f('ix_cnc_data_abertura'), table_name='cnc')
    op.drop_index(op.f('ix_cnc_bfs'), table_name='cnc')
    op.drop_index(op.f('ix_cnc_aplicou_multa'), table_name='cnc')
    op.drop_index('idx_cnc_status_prazo', table_name='cnc')
    op.drop_index('idx_cnc_data_abertura', table_name='cnc')
    op.drop_table('cnc')
    # ### end Alembic commands ###

